@startuml
package src.main.java.upm.etsisi.poo.es{
package command{
interface Command{
 +String INCORRECT
 +String NOTEXIST
 +String EMPTY_TICKET
 +String ID_REPEAT
 +String getName()
 +boolean execute(String fullLine, String[] args)
}
class CommandController{
-Map<String, Command> commands
+{static} CommandController instance
+CommandController()
-void register(Command command)
+Map<String, Command> getCommands()
+boolean handle(String line)
}
class CommandEcho{
+String getName()
+boolean execute(String fullLine, String[] args)
}
class CommandHelp{
+String getName()
+boolean execute(String fullLine, String[] args)
}
class ExitCommand{
+String getName()
+boolean execute(String fullLine, String[] args)
}
class ProductCommand{
+String getName()
+boolean execute(String fullLine, String[] args)
-void prodAdd(String fullLine, String[] args)
-void prodRemove(String[] args)
-void prodUpdate(String fullLine, String[] args, ProductController store)
-prodAddFood(String fullLine, String[] args, ProductController store)
-prodAddMeeting(String fullLine, String[] args, ProductController store)

}

class TicketCommand{
- TicketController controller
+String getName()
+boolean execute(String fullLine, String[] args)
-void ticketAdd(String[] args)
-void ticketRemove(String[] args)
-void ticketPrint(String[] args)
-void ticketList()
}

class CashierCommand{
+String getName()
+boolean execute(String fullLine, String[] args)
-void cashierAdd(String[] args, CashierController cashierController)
-void cashierRemove(String[] args, CashierController cashierController)
-void list(CashierController cashierController)
-void cashTickets(String[] args, CashierController cashierController)
}
class ClientCommand{
+String getName()
+boolean execute(String fullLine, String[] args)
-void clientAdd(String[] args, CustomerController customerController)
-void remove(String[] args, CustomerController customerController)
-void list(CustomerController customerController)
}

}
package user{
abstract class User{
    #String name
    #String email
    #int id
    #TreeMap<Integer, Ticket> tickets
    +String getName()
    +int getId()
    +String getEmail()
}
class Cashier{
    -{static} String UPM_WORKER
    -{static} String ID_ERROR
    -{static} String ID_NOT_FOUND
    +String listTickets()
    +void addTicket(Integer id)
    +Ticket getTicketById(int id)
    +String toString()
    +boolean removeTicket(int id)
}
class Customer{
-int cashierId
+String toString()
+void addTicket(Integer id)
}
class CustomerEnterprise{
+String toString()
}
class CashierController{
-{static} CashierController instance
+{static} String ID_ERROR
-HashMap<Integer, Cashier> cashers
+{static} CashierController getInstance()
+HashMap<Integer, Cashier> getMap()
+boolean addCasher(Integer id, String name, String email)
+void listCashers()
-ArrayList<Cashier> cashersToList()
+void listTicketsOnCasher(int id)
+void addTicket(int ticketId, int cashierId)
+Cashier searchCasherById(int id)
+boolean removeCasher(int id)
+boolean exitsTicket(int cashId, int idTicket)
}
class CustomerController{
+{static} String CASHIER_NOT_FOUND
+{static} CustomerController instance
-TreeMap<Integer, Customer> customers
+{static} CustomerController getInstance()
+void addCustomer(String name, String dni, String email, int cashId)
+int dniToId(String dni)
+Customer getCustomer(int userId)
+boolean removeCustomer(String dni)
+void listCustomers()
-ArrayList<Customer> customersToList()
+void addTicket(Integer ticketId, int userId)
}
}
package product{
abstract class Product{
#int id
#String name
#double price
#{static} String NAME_LENGTH_ERROR
#{static} String NAME_NULL_ERROR
#{static} String PRICE_POSITIVE_ERROR
+{abstract} int getId()
+{abstract}  String getName()
+{abstract} double getPrice()
+{abstract} void setPrice(double price)
+{abstract} void setName(String name)
}

class BasicProduct{
#type category
+int getId()
+String getName()
+double getPrice()
+type getCategory()
+void setId(int id)
+void SetCategory(type category)
+void setName(String name)
+void setPrice(double price)
+double getDiscountedPrice()
+String toString()
+String toStringDiscount()
}

class Event{
#LocalDateTime expiracyDate
#int maxPersonas
#double pricePerPerson
+boolean fechaValida(LocalDateTime time)
+int getMaxPersonas()
+LocalDateTime getExpiryDate()
+String getName()
+int getId()
+double getPrice()
+void setPrice(double price)
+void setName(String name)
+void setmaxPersonas(int maxPersonas)
+double getpricePerPerson()
}

class Food{
-{static} int TIEMPO_MINIMO
+boolean fechaValida(LocalDateTime time)
+String toString()
}

class Meeting{
-{static} int TIEMPO_MINIMO
+boolean fechaValida(LocalDateTime time)
+String toString()
}

class PersonalizedProduct{
-int maxPers
-ArrayList<String> personalizaciones
+String toString()
+boolean addPersonalized(String personalize)
+ String toStringDiscount(double discountValue)
}
class PersonalizedProduct{
-int maxPers
-ArrayList<String> personalizaciones
+int getMaxPers()
+String toString()
+boolean addPersonalized(String personalize)
+void newPrice()
+String toStringDiscount(double discountValue)
}
class ProductController{
+int MAX_PRODUCT
+Product[] productList
+{static} String CASHIER_NOT_FOUND
+{static} String CUSTOMER_NOT_FOUND
+{static} String ID_ERROR
-int prodAmount
-{static} ProductController instance
+{static} ProductController getInstance()
+Product getProduct(int prodId)
+boolean productExits(int prodId)
+boolean addFood(int id, String name, int price, String expiryDate, int assistants)
+boolean addMeeting(int id, String name, double price, String expiryDate, int assistants)
+boolean prodAdd(Product product)
+boolean prodRemove(int id)
+void prodList()
+Product updateType(int id, type category)
+Product updateName(int id, String name)
+Product updatePrice(int id, double price)
}
class Service{
-{static} int NEXT
-String idString
-int id
-LocalDate maxUseDate
-String name
+int getId()
+String getName()
+double getPrice()
+void setPrice(double price)
+void setName(String name)
+LocalDate getMaxUseDate()
+String toString()
}
}
package Tickets{
abstract class Ticket{
 #Integer id
 #Status status
 -{static} int MAX_PRODUCT
 Product[] productList
 #ArrayList<LocalDateTime> dates
 -{static} DateTimeFormatter DATE_FORMAT
 -int amount
 Comparator <Product> nameComp
 +{static} String ERROR_FULL
 #{static} String ERROR_PRODUCT_ID_NOT_FOUND
 #{static} String ADD_OK
 #{static} String MANY_PEOPLE
 #{static} String PERIOD_NOT_VALID
 #{static} String NO_PRODUCTS_IN_THE_TICKET
 #{static} String PRODUCT_DOES_NOT_EXIST
 #{static} String ERROR_TICKET_CLOSE
 #{static} String DONT_CLOSE_NOT_VALID_TIME
 #{static} String TOTAL_PRICE
 #{static} String TOTAL_DISCOUNT
 #{static} String FINAL_PRICE
 #{static} String TICKET
 #{static} String TICKET_NEW_OK
 +Integer getId()
 +Status getStatus()
 +boolean canBeClosed()
 +boolean close()
 +String print(boolean close)
 +String formatList()
 +String toStringId()
 +String toStringNew()
}
class TicketData {
   -{static} String ID_ERROR
   HashMap<Integer, Ticket> tickets
   -{static}TicketData instance
   +{static} TicketData getInstance()
   +Ticket getTicket(int ticketId)
   +int addTicket(String tycketType)
   +boolean addTicket(int idTicket, String ticketType)
}
class TicketController {
    -TicketData ticketData
    +boolean prodAdd(Product product)
    +void ticketNew(String[] args)
    +boolean ticketRemove(int id)
    +String ticketPrint(int id)
}
class CustomerTicket{
+String print(boolean close)
+boolean canBeClosed()
+boolean ticketAdd(Product product, int amount)
+Product ticketRemove(int prodId)
+boolean comprobarFechasTodosEventos(LocalDateTime now)
+String ticketPrint(boolean close)
+void sort()
}
class EnterpriseMixedTicket{
-List<Product> products
-List<Service> services
+boolean canBeClosed()
+double getExtraDiscountRate()
+boolean addProduct(Product p, int amount)
+List<Product> getProducts()
+List<Service> getServices()
+String print(boolean close)
+Product ticketRemove(int prodId)
+String toStringNew()
}
class EnterpriseServiceTicket{
-String INCORRECT
-List<Service> services
+boolean canBeClosed()
+boolean addService(Service s)
+List<Service> getServices()
+String print( boolean close)
+Service ticketRemove(int prodId)
+String toStringNew()
}
enum Status{
 - EMPTY
 - ACTIVE
 - CLOSED
}
}
class App{
 -{static} String WELCOME_MESSAGE
 -{static} String HELP_MESSAGE
 -{static} String FILE_ERROR
 -{static} String TERMINAL_ERROR
 -{static} String UPM
 -{static} final Map<String, List<String>> COMMANDS
 +main(String[] args)
 -void end()
 -void start()
 -void userCommand()
 -void readFile(String[] args)
 -void init()
}
enum type{
 -MERCH
 -STATIONARY
 -CLOTHES
 -BOOK
 -ELECTRONICS
}
App ..> CommandController : uses
User <|- Cashier
User <|-- Customer
Command <|.. CommandEcho
Command <|.. CommandHelp
Command <|.. ExitCommand
Command <|.. ProductCommand
Command <|.. TicketCommand
Command <|.. CashierCommand
Command <|.. ClientCommand
CommandController "0" --o "many" Command : keeps
CommandController ..> Command
ProductCommand ..> ProductController
TicketCommand --* TicketController
CashierCommand ..> CashierController
User"0" ---o "N" Ticket
TicketData *-- Ticket
Product <|.. BasicProduct
Product <|.. Event
Event <|.. Food
Event <|.. Meeting
BasicProduct <|.. PersonalizedProduct
Store "0"*-- "200" Product : has_on_stock
Store ..> Product
Ticket "0"--o "100" Product : contains
Ticket --|> Store
TicketData --* TicketCommand
CustomerController ..|> TicketData
CashierController ..|> TicketData
CashierCommand *-- CashierController
TicketCommand *-- TicketController
ClientCommand *-- CustomerController
TicketController ..|> TicketData
CashierController <|. CustomerController
CashierController *-- Cashier
CustomerController +-- Customer
TicketController --> Store
}
@enduml
@enduml
